# Generated by Django 4.2.5 on 2023-11-03 05:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('W', 'White'), ('K', 'Black'), ('B', 'Blue'), ('G', 'Green'), ('R', 'Red'), ('T', 'Transparent'), ('M', 'Multi'), ('D', 'Default')], max_length=1, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_active', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, verbose_name='About')),
                ('product_type', models.CharField(choices=[('SK', 'Sticker'), ('TS', 'Short Sleeve T-shirt'), ('TL', 'Long Sleeve T-shirt'), ('HZ', 'Zip-Up Hoodie'), ('HP', 'Pull-Over Hoodie'), ('CP', 'Cap'), ('MS', 'Miscellaneous')], max_length=2)),
                ('image', models.ImageField(upload_to='uploads/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('SM', 'Small'), ('MD', 'Medium'), ('LG', 'Large'), ('XL', 'Extra-Large')], max_length=2, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.PositiveIntegerField()),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aintdoinit.color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aintdoinit.product')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aintdoinit.size')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aintdoinit.cart')),
                ('product_variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aintdoinit.productvariation')),
            ],
        ),
    ]
