# Generated by Django 4.2.5 on 2023-10-31 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('W', 'White'), ('K', 'Black'), ('B', 'Blue'), ('G', 'Green'), ('R', 'Red')], max_length=1, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_active', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, verbose_name='About')),
                ('product_type', models.CharField(choices=[('SK', 'Sticker'), ('TS', 'Short Sleeve T-shirt'), ('TL', 'Long Sleeve T-shirt'), ('HZ', 'Zip-Up Hoodie '), ('HP', 'Pull-Over Hoodie'), ('CP', 'Cap'), ('MS', 'Miscellaneous')], max_length=2)),
                ('image', models.ImageField(upload_to='uploads/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('SM', 'Small'), ('MD', 'Medium'), ('LG', 'Large'), ('XL', 'Extra-Large')], max_length=2, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colors', models.ManyToManyField(to='aintdoinit.color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aintdoinit.product')),
                ('sizes', models.ManyToManyField(to='aintdoinit.size')),
            ],
        ),
    ]
