# Generated by Django 4.2.5 on 2023-11-02 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aintdoinit', '0002_productvariation_delete_mod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('SK', 'Sticker'), ('TS', 'Short Sleeve T-shirt'), ('TL', 'Long Sleeve T-shirt'), ('HZ', 'Zip-Up Hoodie'), ('HP', 'Pull-Over Hoodie'), ('CP', 'Cap'), ('MS', 'Miscellaneous')], max_length=2),
        ),
    ]
