# Generated by Django 4.2.5 on 2023-11-02 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aintdoinit', '0004_cart_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='value',
            field=models.CharField(choices=[('W', 'White'), ('K', 'Black'), ('B', 'Blue'), ('G', 'Green'), ('R', 'Red'), ('T', 'Transparent'), ('M', 'Multi'), ('D', 'Default')], max_length=1, unique=True),
        ),
    ]
